### ISSUE TITLE
Google OAuth won't work in 1.92.0.

### ISSUE THREAD

**Issue by XPMUser** [Toonigy/ProdiPlus#4]
[PRODIGY][ERROR] Login.onGoogleAuthLoaded - error loading google auth lib. The error is: idpiframe_initialization_failed  details: Not a valid origin for the client: https://toonigy.github.io has not been registered for client ID 523759519115-63c0h2vhev83mq90pq4c746ncnnpeh1o.apps.googleusercontent.com. Please go to https://console.developers.google.com/ and register this origin for your project's client ID.
game.min.js:213 [PRODIGY][ERROR] Login.authorizeWithGoogle - the Google auth2 lib is not loaded so we can't prompt for google credentials

**Comment by Toonigy** [comment]
i wont fix it
